
DEFAULT_LOCATION = {'location' : {'country' : {'id' : "Unknown", 'name' : "Unknown"}, 'level' : 0}}

LANGS_COUNTRIES = {
    'EN' : ['au', 'us', 'uk', 'gov', 'za', 'ca', 'ie', 'nz', 'zw', 'durban', 'eu', 'in', 'tt', 'tz', 'com', 'city', 'int', 'org', 'int', 'earth', 'edu', 'io', 'group', 'tools', 'net', 'science', 'sg', 'tc', 'cymru', 'ag', 'asia', 'ai', 'info', 'scot', 'aq', 'rw', 'bb', 'mt', 'lk', 'ug', 'ng', 'zm'],
    'MN' : ['mn'],
    'LT' : ['lt'],
    'ES' : ['es', 'ar', 'sv', 'mx', 'cl', 'gt', 'hn', 'ec', 'cr', 'pe', 'cat', 'py', 'bo', 'uy', 'gal', 'eus', 'do', 'ad'],
    'JP' : ['jp'],
    'DE' : ['at', 'de', 'ch'],
    'FR' : ['fr', 'ci', 'tg', 'be', 'lu', 'corsica', 'bzh', 'bf', 'cd'],
    'RU' : ['ru', 'by'],
    'DA' : ['dk', 'fo', 'gl'],
    'FI' : ['fi'],
    'NL' : ['nl'],
    'BG' : ['bg'],
    'AR' : ['bh', 'sa', 'ps', 'tn', 'lb', 'ma', 'kw', 'abudhabi', 'ae', 'sd'],
    'IT' : ['it'],
    'PT' : ['pt', 'mz', 'br'],
    'TH' : ['th'],
    'TR' : ['tr'],
    'EL' : ['gr', 'cy'],
    'VN' : ['vn'],
    'CN' : ['cn'],
    'SR' : ['me', 'rs', 'ba'],
    'AL' : ['al'],
    'LV' : ['lv'],
    'PL' : ['pl'],
    'LA' : ['lo'],
    'AM' : ['am'],
    'SV' : ['se'],
    'zh_TW' : ['tw'],
    'zh_CN' : ['cn', 'mo'],   
    'SL' : ['si'],
    'NO' : ['no'],
    'RO' : ['ro'], 
    'ID' : ['id'],
    'ET' : ['ee'],
    'HU' : ['hu'],
    'KR' : ['kr'],
    'CZ' : ['cz'],
    'KA' : ['ge'],
    'HE' : ['il'],
    'SK' : ['sk'],
    'NE' : ['np'],
    'HR' : ['hr'],
    'MK' : ['mk'],
    'MD' : ['md'],
    'DZ' : ['bt'],
    'IS' : ['is'],
    'UK' : ['ua']
}

def reverse_langs():
    reversed = {}
    for k, v in LANGS_COUNTRIES.items():
        for dm in v:
            reversed[dm] = k
    return reversed

COUNTRIES_LANGS = reverse_langs()


DOMAIN_LOCATIONS = {
    'co' : {'location' : {'country' : {'id' : "CO", 'name' : "Colombia"}, 'level' : 2}},
    'au' : {'location' : {'country' : {'id' : "AU", 'name' : "Australia"}, 'level' : 2}},
    'uk' : {'location' : {'country' : {'id' : "GB", 'name' : "United Kingdom"}, 'level' : 2}},
    'mn' : {'location' : {'country' : {'id' : "MN", 'name' : "Mongolia"}, 'level' : 2}},
    'lt' : {'location' : {'country' : {'id' : "LT", 'name' : "Lithuania"}, 'level' : 2}},
    'com' : {'location' : {'country' : {'id' : "Unknown", 'name' : "Unknown"}, 'level' : 2}},
    'za' : {'location' : {'country' : {'id' : "ZA", 'name' : "South Africa"}, 'level' : 2}},
    'zw' : {'location' : {'country' : {'id' : "ZW", 'name' : "Zimbabwe"}, 'level' : 2}},
    'tt' : {'location' : {'country' : {'id' : "TT", 'name' : "Trinidad and Tobago"}, 'level' : 2}},
    'city' : {'location' : {'country' : {'id' : "Unknown", 'name' : "Unknown"}, 'level' : 2}},
    'gov' : {'location' : {'country' : {'id' : "US", 'name' : "United States"}, 'level' : 2}},
    'org' : {'location' : {'country' : {'id' : "Unknown", 'name' : "Unknown"}, 'level' : 2}},
    'ca' : {'location' : {'country' : {'id' : "CA", 'name' : "Canada"}, 'level' : 2}},
    'ie' : {'location' : {'country' : {'id' : "IE", 'name' : "Ireland"}, 'level' : 2}},
    'nz' : {'location' : {'country' : {'id' : "NZ", 'name' : "New Zealand"}, 'level' : 2}},
    'dk' : {'location' : {'country' : {'id' : "DK", 'name' : "Denmark"}, 'level' : 2}},
    'us' : {'location' : {'country' : {'id' : "US", 'name' : "United States"}, 'level' : 2}},
    'at' : {'location' : {'country' : {'id' : "AT", 'name' : "Austria"}, 'level' : 2}},
    'es' : {'location' : {'country' : {'id' : "ES", 'name' : "Spain"}, 'level' : 2}},
    'ci' : {'location' : {'country' : {'id' : "CI", 'name' : "Cote d Ivoire"}, 'level' : 2}},
    'jp' : {'location' : {'country' : {'id' : "JP", 'name' : "Japan"}, 'level' : 2}},
    'it' : {'location' : {'country' : {'id' : "IT", 'name' : "Italy"}, 'level' : 2}},
    'fo' : {'location' : {'country' : {'id' : "FO", 'name' : "Faroe Islands"}, 'level' : 2}},
    'int' : {'location' : {'country' : {'id' : "World", 'name' : "World"}, 'level' : 2}},
    'cat' : {'location' : {'country' : {'id' : "ES", 'name' : "Spain"}, 'level' : 3, 'subregion': {'id' : 'ES-CT'}}},
    'tg' : {'location' : {'country' : {'id' : "TG", 'name' : "Togo"}, 'level' : 2}},
    'me' : {'location' : {'country' : {'id' : "ME", 'name' : "Montenegro"}, 'level' : 2}},
    'by' : {'location' : {'country' : {'id' : "BY", 'name' : "Belarus"}, 'level' : 2}},
    'fi' : {'location' : {'country' : {'id' : "FI", 'name' : "Finland"}, 'level' : 2}},
    'bg' : {'location' : {'country' : {'id' : "BG", 'name' : "Bulgaria"}, 'level' : 2}},
    'bh' : {'location' : {'country' : {'id' : "BH", 'name' : "Bahrein"}, 'level' : 2}},
    'tz' : {'location' : {'country' : {'id' : "TZ", 'name' : "Tanzania"}, 'level' : 2}},
    'mz' : {'location' : {'country' : {'id' : "MX", 'name' : "Mozambique"}, 'level' : 2}},
    'vn' : {'location' : {'country' : {'id' : "VN", 'name' : "Vietnam"}, 'level' : 2}},
    'sg' : {'location' : {'country' : {'id' : "SG", 'name' : "Singapore"}, 'level' : 2}},
    'lv' : {'location' : {'country' : {'id' : "LV", 'name' : "Latvia"}, 'level' : 2}},
    'al' : {'location' : {'country' : {'id' : "AL", 'name' : "Albania"}, 'level' : 2}},
    'la' : {'location' : {'country' : {'id' : "LA", 'name' : "Laos"}, 'level' : 2}},
    'nl' : {'location' : {'country' : {'id' : "NL", 'name' : "Netherlands"}, 'level' : 2}},
    'th' : {'location' : {'country' : {'id' : "TH", 'name' : "Thailand"}, 'level' : 2}},
    'ru' : {'location' : {'country' : {'id' : "RU", 'name' : "Russian Federation"}, 'level' : 2}},
    'ps' : {'location' : {'country' : {'id' : "PS", 'name' : "Palestine"}, 'level' : 2}},
    'sa' : {'location' : {'country' : {'id' : "SA", 'name' : "Saudi Arabia"}, 'level' : 2}},
    'io' : {'location' : {'country' : {'id' : "Unknown", 'name' : "Unknown"}, 'level' : 2}},
    'tc' : {'location' : {'country' : {'id' : "TC", 'name' : "Turks and Caicos Islands"}, 'level' : 2}},
    'edu' : {'location' : {'country' : {'id' : "Unknown", 'name' : "Unknown"}, 'level' : 2}},
    'de' : {'location' : {'country' : {'id' : "DE", 'name' : "Germany"}, 'level' : 2}},
    'ar' : {'location' : {'country' : {'id' : "AR", 'name' : "Argentina"}, 'level' : 2}},
    'eu' : {'location' : {'country' : {'id' : "EU", 'name' : "European Union"}, 'level' : 2}},
    'group' : {'location' : {'country' : {'id' : "Unknown", 'name' : "Unknown"}, 'level' : 2}},
    'pl' : {'location' : {'country' : {'id' : "PL", 'name' : "Poland"}, 'level' : 2}},
    'sv' : {'location' : {'country' : {'id' : "SV", 'name' : "El Salvador"}, 'level' : 2}},
    'tools' : {'location' : {'country' : {'id' : "Unknown", 'name' : "Unknown"}, 'level' : 2}},
    'tw' : {'location' : {'country' : {'id' : "TW", 'name' : "Taiwan"}, 'level' : 2}},
    'id' : {'location' : {'country' : {'id' : "ID", 'name' : "Indonesia"}, 'level' : 2}},
    'mx' : {'location' : {'country' : {'id' : "MX", 'name' : "Mexico"}, 'level' : 2}},
    'kr' : {'location' : {'country' : {'id' : "KR", 'name' : "South Korea"}, 'level' : 2}},
    'gr' : {'location' : {'country' : {'id' : "GR", 'name' : "Greece"}, 'level' : 2}},
    'in' : {'location' : {'country' : {'id' : "IN", 'name' : "India"}, 'level' : 2}},
    'ec' : {'location' : {'country' : {'id' : "EC", 'name' : "Ecuador"}, 'level' : 2}},
    'durban' : {'location' : {'country' : {'id' : "ZA", 'name' : "South Africa"}, 'level' : 3, 'subregion' : {'id' : 'ZA-KZN'}}},
    'cn' : {'location' : {'country' : {'id' : "CN", 'name' : "China"}, 'level' : 2}},
    'net' : {'location' : {'country' : {'id' : "Unknown", 'name' : "Unknown"}, 'level' : 2}},
    'gt' : {'location' : {'country' : {'id' : "GT", 'name' : "Guatemala"}, 'level' : 2}},
    'cz' : {'location' : {'country' : {'id' : "CZ", 'name' : "Czech Republic"}, 'level' : 2}},
    'lk' : {'location' : {'country' : {'id' : "LK", 'name' : "Sri Lanka"}, 'level' : 2}},
    'tr' : {'location' : {'country' : {'id' : "TR", 'name' : "Turkey"}, 'level' : 2}},
    'cy' : {'location' : {'country' : {'id' : "CY", 'name' : "Cyprus"}, 'level' : 2}},
    'hn' : {'location' : {'country' : {'id' : "HN", 'name' : "Honduras"}, 'level' : 2}},
    'se' : {'location' : {'country' : {'id' : "SE", 'name' : "Sweden"}, 'level' : 2}},
    'ch' : {'location' : {'country' : {'id' : "CH", 'name' : "Switzerland"}, 'level' : 2}},
    'swiss' : {'location' : {'country' : {'id' : "CH", 'name' : "Switzerland"}, 'level' : 2}},
    'sk' : {'location' : {'country' : {'id' : "SK", 'name' : "Slovakia"}, 'level' : 2}},
    'ba' : {'location' : {'country' : {'id' : "BA", 'name' : "Bosnia and Herzegovina"}, 'level' : 2}},
    'cr' : {'location' : {'country' : {'id' : "CR", 'name' : "Costa Rica"}, 'level' : 2}},
    'pe' : {'location' : {'country' : {'id' : "PE", 'name' : "Peru"}, 'level' : 2}},
    'fr' : {'location' : {'country' : {'id' : "FR", 'name' : "France"}, 'level' : 2}},
    'br' : {'location' : {'country' : {'id' : "BR", 'name' : "Brazil"}, 'level' : 2}},
    'lu' : {'location' : {'country' : {'id' : "LU", 'name' : "Luxemburg"}, 'level' : 2}},
    'be' : {'location' : {'country' : {'id' : "BE", 'name' : "Belgium"}, 'level' : 2}},
    'si' : {'location' : {'country' : {'id' : "SI", 'name' : "Slovenia"}, 'level' : 2}},
    'no' : {'location' : {'country' : {'id' : "NO", 'name' : "Norway"}, 'level' : 2}},
    'ag' : {'location' : {'country' : {'id' : "AG", 'name' : "Antigua and Barbuda"}, 'level' : 2}},
    'ro' : {'location' : {'country' : {'id' : "RO", 'name' : "Romania"}, 'level' : 2}},
    'cl' : {'location' : {'country' : {'id' : "CL", 'name' : "Chile"}, 'level' : 2}},
    'earth' : {'location' : {'country' : {'id' : "Unknown", 'name' : "Unknown"}, 'level' : 2}},
    'cymru' : {'location' : {'country' : {'id' : "GB", 'name' : "United Kingdom"}, 'level' : 3, 'subregion' : {'id' : "GB-WLS"}}},
    'sd' : {'location' : {'country' : {'id' : "SD", 'name' : "Sudan"}, 'level' : 2}},
    'bo' : {'location' : {'country' : {'id' : "BO", 'name' : "Bolivia"}, 'level' : 2}},
    'np' : {'location' : {'country' : {'id' : "NP", 'name' : "Nepal"}, 'level' : 2}},
    'hr' : {'location' : {'country' : {'id' : "HR", 'name' : "Croatia"}, 'level' : 2}},
    'uy' : {'location' : {'country' : {'id' : "UY", 'name' : "Uruguay"}, 'level' : 2}},
    'tn' : {'location' : {'country' : {'id' : "TN", 'name' : "Tunis"}, 'level' : 2}},
    'rw' : {'location' : {'country' : {'id' : "RW", 'name' : "Rwanda"}, 'level' : 2}},
    'iq' : {'location' : {'country' : {'id' : "IQ", 'name' : "Iraq"}, 'level' : 2}},
    'rs' : {'location' : {'country' : {'id' : "RS", 'name' : "Serbia"}, 'level' : 2}},
    'py' : {'location' : {'country' : {'id' : "PY", 'name' : "Paraguay"}, 'level' : 2}},
    'pt' : {'location' : {'country' : {'id' : "PT", 'name' : "Portugal"}, 'level' : 2}},
    'mt' : {'location' : {'country' : {'id' : "MT", 'name' : "Malta"}, 'level' : 2}},
    'mk' : {'location' : {'country' : {'id' : "MK", 'name' : "Makedonia"}, 'level' : 2}},
    'md' : {'location' : {'country' : {'id' : "MD", 'name' : "Moldavia"}, 'level' : 2}},
    'lb' : {'location' : {'country' : {'id' : "LB", 'name' : "Lebanon"}, 'level' : 2}},
    'do' : {'location' : {'country' : {'id' : "DO", 'name' : "Dominican Republic"}, 'level' : 2}},
    'bf' : {'location' : {'country' : {'id' : "BF", 'name' : "Burkina Faso"}, 'level' : 2}},
    'hu' : {'location' : {'country' : {'id' : "HU", 'name' : "Hungary"}, 'level' : 2}},
    'am' : {'location' : {'country' : {'id' : "AM", 'name' : "Armenia"}, 'level' : 2}},
    'aq' : {'location' : {'country' : {'id' : "Unknown", 'name' : "Unknown"}, 'level' : 2}},
    'bt' : {'location' : {'country' : {'id' : "BT", 'name' : "Bhutan"}, 'level' : 2}},
    'ge' : {'location' : {'country' : {'id' : "GE", 'name' : "Georgia"}, 'level' : 2}},
    'ci' : {'location' : {'country' : {'id' : "CI", 'name' : "Republic of Ivory Coast"}, 'level' : 2}},
    'ad' : {'location' : {'country' : {'id' : "AD", 'name' : "Andorra"}, 'level' : 2}},
    'bb' : {'location' : {'country' : {'id' : "BB", 'name' : "Barbados"}, 'level' : 2}},
    'ma' : {'location' : {'country' : {'id' : "MA", 'name' : "Marocco"}, 'level' : 2}},
    'ai' : {'location' : {'country' : {'id' : "Unknown", 'name' : "Unknown"}, 'level' : 2}},
    'kw' : {'location' : {'country' : {'id' : "KW", 'name' : "Kuwait"}, 'level' : 2}},
    'asia' : {'location' : {'country' : {'id' : "Unknown", 'name' : "Unknown"}, 'level' : 2}},
    'il' : {'location' : {'country' : {'id' : "IL", 'name' : "Israel"}, 'level' : 2}},
    'ae' : {'location' : {'country' : {'id' : "AE", 'name' : "United Arab Emirates"}, 'level' : 2}},
    'ug' : {'location' : {'country' : {'id' : "UG", 'name' : "Uganda"}, 'level' : 2}},
    'info' : {'location' : {'country' : {'id' : "Unknown", 'name' : "Unknown"}, 'level' : 2}},
    'abudhabi' : {'location' : {'country' : {'id' : "AE", 'name' : "United Arab Emirates"}, 'level' : 3, 'subregion' : {'id' : "AE-AZ"}}},
    'gal' :{'location' : {'country' : {'id' : "ES", 'name' : "Spain"}, 'level' : 3, 'subregion' : {'id' : "ES-GA"}}},
    'eus' : {'location' : {'country' : {'id' : "ES", 'name' : "Spain"}, 'level' : 3, 'subregion': {'id' : 'ES-PV'}}},
    'mo' : {'location' : {'country' : {'id' : "MO", 'name' : "Macau"}, 'level' : 2}},
    'corsica' : {'location' : {'country' : {'id' : "FR", 'name' : "France"}, 'level' : 3, 'subregion' : 'FR-20R'}},
    'bzh' : {'location' : {'country' : {'id' : "FR", 'name' : "France"}, 'level' : 2}},
    'cd' : {'location' : {'country' : {'id' : "CD", 'name' : "Democratic Republic of the Congo"}, 'level' : 2}},
    'is' : {'location' : {'country' : {'id' : "IS", 'name' : "Iceland"}, 'level' : 2}},
    'ua' : {'location' : {'country' : {'id' : "UA", 'name' : "Ukraine"}, 'level' : 2}},
    'ee' : {'location' : {'country' : {'id' : "EE", 'name' : "Estonia"}, 'level' : 2}},
    'scot' : {'location' : {'country' : {'id' : "GB", 'name' : "United Kingdom"}, 'level' : 3, 'subregion' : {'id' : 'GB-SCT'}}},
    'gl' : {'location' : {'country' : {'id' : "GL", 'name' : "Greenland"}, 'level' : 2}},
    'science' : {'location' : {'country' : {'id' : "Unknown", 'name' : "Unknown"}, 'level' : 2}},
    'ng' : {'location' : {'country' : {'id' : "NG", 'name' : "Nigeria"}, 'level' : 2}},
    'dz' : {'location' : {'country' : {'id' : "DZ", 'name' : "Algeria"}, 'level' : 2}},
    'cv' : {'location' : {'country' : {'id' : "CV", 'name' : "Cabo Verde"}, 'level' : 2}},
    'et' : {'location' : {'country' : {'id' : "ET", 'name' : "Ethiopia"}, 'level' : 2}},
    'bd' : {'location' : {'country' : {'id' : "BD", 'name' : "Bangladesh"}, 'level' : 2}},
    'ml' : {'location' : {'country' : {'id' : "ML", 'name' : "Mali"}, 'level' : 2}},
    'ir' : {'location' : {'country' : {'id' : "IR", 'name' : "Iran"}, 'level' : 2}},
    'pk' : {'location' : {'country' : {'id' : "PK", 'name' : "Pakistan"}, 'level' : 2}},
    'taipei' : {'location' : {'country' : {'id' : "TW", 'name' : "Taiwan"}, 'level' : 3}, 'subregion' : {'id' : 'TW-TPE'}},
    'mv' : {'location' : {'country' : {'id' : "MV", 'name' : "Maldives"}, 'level' : 2}},
    'gh' : {'location' : {'country' : {'id' : "GH", 'name' : "Ghana"}, 'level' : 2}},
    'cm' : {'location' : {'country' : {'id' : "CM", 'name' : "Cameroon"}, 'level' : 2}},
    'nrw' : {'location' : {'country' : {'id' : "DE", 'name' : "Germany"}, 'level' : 3}, 'subregion' : {'id' : 'DE-NW'}},
    'na' : {'location' : {'country' : {'id' : "NA", 'name' : "Namibia"}, 'level' : 2}},
    'kh' : {'location' : {'country' : {'id' : "KH", 'name' : "Cambodia"}, 'level' : 2}},
    'bj' : {'location' : {'country' : {'id' : "BJ", 'name' : "Benin"}, 'level' : 2}},
    'hk' : {'location' : {'country' : {'id' : "HK", 'name' : "Hong Kong"}, 'level' : 2}},
    'sn' : {'location' : {'country' : {'id' : "SN", 'name' : "Senegal"}, 'level' : 2}},
    'pr' : {'location' : {'country' : {'id' : "US", 'name' : "United States"}, 'level' : 3, 'subregion' : {'id' : "US-PR"}}},
    'ke' : {'location' : {'country' : {'id' : "KE", 'name' : "Kenya"}, 'level' : 2}},
    'tf' : {'location' : {'country' : {'id' : "FR", 'name' : "France"}, 'level' : 3, 'subregion' : {'id' : "FR-TF"}}},
    'my' : {'location' : {'country' : {'id' : "MY", 'name' : "Malaysia"}, 'level' : 2}},
    'paris' : {'location' : {'country' : {'id' : "FR", 'name' : "France"}, 'level' : 3, 'subregion' : {'id' : "FR-75C"}}},
    'nc' : {'location' : {'country' : {'id' : "FR", 'name' : "France"}, 'level' : 3, 'subregion' : {'id' : "FR-NC"}}},
    'ph' : {'location' : {'country' : {'id' : "PH", 'name' : "Phillipines"}, 'level' : 2}},
    'li' : {'location' : {'country' : {'id' : "LI", 'name' : "Liechtenstein"}, 'level' : 2}},
    'wales' : {'location' : {'country' : {'id' : "GB", 'name' : "United Kingdom"}, 'level' : 3, 'subregion' : {'id' : "GB-WLS"}}},
    'ruhr' : {'location' : {'country' : {'id' : "DE", 'name' : "Germany"}, 'level' : 3}, 'subregion' : {'id' : 'DE-NW'}},
    'mil' : {'location' : {'country' : {'id' : "US", 'name' : "United States"}, 'level' : 2}},
    'brussels' : {'location' : {'country' : {'id' : "BE", 'name' : "Belgium"}, 'level' : 3, 'subregion' : {'id' : "BE-BRU"}}},
    'gi' : {'location' : {'country' : {'id' : "GB", 'name' : "United Kingdom"}, 'level' : 2}},
    've' : {'location' : {'country' : {'id' : "VE", 'name' : "Venezuela"}, 'level' : 2}},
    'ax' : {'location' : {'country' : {'id' : "FI", 'name' : "Finland"}, 'level' : 3, 'subregion' : {'id' : "FI-01"}}},
    'jm' : {'location' : {'country' : {'id' : "JM", 'name' : "Jamaica"}, 'level' : 2}},
    'sc' : {'location' : {'country' : {'id' : "SC", 'name' : "Seychelles"}, 'level' : 2}},
    'cu' : {'location' : {'country' : {'id' : "CU", 'name' : "Cuba"}, 'level' : 2}},
    'pf' : {'location' : {'country' : {'id' : "FR", 'name' : "France"}, 'level' : 3, 'subregion' : {'id' : "FR-PF"}}},
    'ls' : {'location' : {'country' : {'id' : "LS", 'name' : "Lesotho"}, 'level' : 2}},
    'dm' : {'location' : {'country' : {'id' : "DM", 'name' : "Dominica"}, 'level' : 2}},
    'zm' : {'location' : {'country' : {'id' : "ZM", 'name' : "Zambia"}, 'level' : 2}},
    'tt' : {'location' : {'country' : {'id' : "TT", 'name' : "Trinidad and Tobago"}, 'level' : 2}},
    'qa' : {'location' : {'country' : {'id' : "QA", 'name' : "Qatar"}, 'level' : 2}},
    'pg' : {'location' : {'country' : {'id' : "PG", 'name' : "Papua New Guinea"}, 'level' : 2}},
    'om' : {'location' : {'country' : {'id' : "OM", 'name' : "Oman"}, 'level' : 2}},
    'nu' : {'location' : {'country' : {'id' : "NU", 'name' : "Niue"}, 'level' : 2}},
    'fj' : {'location' : {'country' : {'id' : "FJ", 'name' : "Fiji"}, 'level' : 2}},
    'az' : {'location' : {'country' : {'id' : "AZ", 'name' : "Azerbaijan"}, 'level' : 2}},
    'ni' : {'location' : {'country' : {'id' : "NI", 'name' : "Nicaragua"}, 'level' : 2}},
    'uz' : {'location' : {'country' : {'id' : "UZ", 'name' : "Uzbekistan"}, 'level' : 2}},
    'pa' : {'location' : {'country' : {'id' : "PA", 'name' : "Paraguay"}, 'level' : 2}},
}


MAP_CATALOG_TYPE_SUBDIR = {'Metadata catalog' : 'metadata', 
    'Geoportal' : 'geo', 
    'Scientific data repository' : 'scientific',
    'API Catalog' : 'api',
    'Machine learning catalog' : 'ml',
    'Data search engines' : 'search',
    'Indicators catalog' : 'indicators'
}

MAP_SOFTWARE_OWNER_CATALOG_TYPE = {
    'ckan' : "Open data portal", 
    'dkan' : 'Open data portal',
    'datapress' : 'Open data portal',
    'drupal' : 'Open data portal',
    'arcgishub' : "Geoportal",
    "arcgisserver" : "Geoportal",
    "geonetwork" : "Geoportal",
    "geonode" : "Geoportal",
    "carto" : "Geoportal",    
    "geoblacklight" : "Geoportal",
    "geoserver" : "Geoportal",    
    'api' : "API Catalog",
    'fusionregistry' : "Metadata catalog",
    'metadataregistries' : "Metadata catalog",
    'microdata' : "Microdata catalog",
    'nada' : "Microdata catalog",
    "datalad" : "Scientific data repository",
    'converis' : "Scientific data repository",
    "dspace" : "Scientific data repository",
    "eprints" : "Scientific data repository",
    "esploro" : "Scientific data repository",
    "erdasapollo" : "Geoportal",
    "figshare" : "Scientific data repository",
    "galaxy" : "Scientific data repository",
    "indicators" : "Indicators catalog",
    "opensdg" : "Indicators catalog",
    "pxweb" : "Indicators catalog",
    "invenio" : "Scientific data repository",
    "ipt" : "Scientific data repository",
    "mytardis" : "Scientific data repository",
    "omegapsir" : "Scientific data repository",
    "pure" : "Scientific data repository",
    "samvera" : "Scientific data repository",
    "scientific" : "Scientific data repository",
    "opengeoportal" : "Geoportal",
    "othergeo" : "Geoportal",
    "oskari" : "Geoportal",
    "ml" : "Machine learning catalog",
    "opendatasoft" : "Open data portal",
    "opendata" : "Open data portal",
    "publishmydata" : "Open data portal",
    "tablion" : "Open data portal",
    "socrata" : "Open data portal",
    "wordpress" : "Open data portal",
    "searchengines" : "Data search engines",
    "mapproxy" : "Geoportal",
    "pygeoapi" : "Geoportal",
    "smartdatasdi" : "Geoportal",
    "lizmap" : "Geoportal",
    "mapbender" : "Geoportal",
    "colectica" : "Microdata catalog",
    "statsuite" : "Indicators catalog"
}

CUSTOM_SOFTWARE_KEYS = ['searchengines', 'ml', 'opendata', 'indicators', 'scientific', 'metadataregistries', 'api']


ENTRY_TEMPLATE = {"access_mode": ["open"], 
"api": False, "api_status": "uncertain", 
"catalog_type": 'Unknown', 
"content_types": ["dataset"], 
"coverage": [], "id": "None", "langs": [], 
"link": None, "name": "", 
"owner": {"link": None, "location": None, "name": "", "type": "Unknown"}, 
"software": {"id": None, "name": None}, 
"status": "scheduled", 
"tags": [], "topics": [],
'description' : 'This is a temporary record with some data collected but it should be updated befor adding to the index'
}


COUNTRIES = { "AD" : "Andorra",
"AE" : "United Arab Emirates",
"Africa" : "Africa",
"AL" : "Albania",
"AM" : "Armenia",
"AO" : "Angola",
"AR" : "Argentina",
"AS" : "Samoa",
"ASEAN" : "ASEAN",
"AT" : "Austria",
"AU" : "Australia",
"AZ" : "Azerbaijan",
"BA" : "Bosnia and Herzegovina",
"BD" : "Bangladesh",
"BE" : "Belgium",
"LU" : "Luxembourg",
"BF" : "Burkina Faso",
"BG" : "Bulgaria",
"BH" : "Bahrain",
"BI" : "Burundi",
"BJ" : "Benin",
"BN" : "Brunei",
"BO" : "Bolivia",
"BR" : "Brazil",
"BW" : "Botswana",
"BY" : "Belarus",
"BZ" : "Belize",
"CA" : "Canada",
"World" : "World",
"Caribbean" : "Caribbean",
"CH" : "Switzerland",
"CI" : "Cote d Ivoire",
"CL" : "Chile",
"CM" : "Cameroon",
"CN" : "China",
"CO" : "Colombia",
"CR" : "Costa Rica",
"CV" : "Cabo Verde",
"CY" : "Cyprus",
"CZ" : "Czech Republic",
"DE" : "Germany",
"YE" : "Yemen",
"DK" : "Denmark",
"DM" : "Dominica",
"DO" : "Republica Dominicana",
"DZ" : "Algeria",
"EC" : "Ecuador",
"EE" : "Estonia",
"EG" : "Egypt",
"ES" : "Spain",
"ET" : "Ethiopia",
"EU" : "European Union",
"FI" : "Finland",
"FR" : "France",
"GM" : "Gambia",
"GB" : "United Kingdom",
"FJ" : "Fiji",
"GE" : "Georgia",
"GH" : "Ghana",
"GR" : "Greece",
"GT" : "Guatemala",
"HK" : "Hong Kong",
"HR" : "Croatia",
"HT" : "Haiti",
"HU" : "Hungary",
"ID" : "Indonesia",
"IE" : "Ireland",
"IL" : "Israel",
"IN" : "India",
"IR" : "Iran",
"IS" : "Iceland",
"IT" : "Italy",
"AQ" : "Antarctic",
"JM" : "Jamaica",
"JO" : "Jordan",
"JP" : "Japan",
"KE" : "Kenya",
"KG" : "Kyrgyzstan",
"KH" : "Cambodia",
"KR" : "South Korea",
"KZ" : "Kazakhstan",
"LA" : "Laos",
"LatinAmerica" : "Latin America",
"LB" : "Lebanon",
"LK" : "Sri Lanka",
"LT" : "Lithuania",
"LV" : "Latvia",
"MA" : "Morocco",
"MD" : "Moldova",
"ME" : "Montenegro",
"MG" : "Madagascar",
"MK" : "Republic of North Macedonia",
"ML" : "Mali",
"MM" : "Myanmar",
"MN" : "Mongolia",
"MR" : "Mauritania",
"MT" : "Malta",
"MW" : "Malawi",
"MX" : "Mexico",
"MY" : "Malaysia",
"MZ" : "Mozambique",
"PT" : "Portugal",
"NA" : "Namibia",
"NG" : "Nigeria",
"NI" : "Nicaragua",
"NL" : "Netherlands",
"NO" : "Norway",
"NP" : "Nepal",
"NZ" : "New Zealand",
"Oceania" : "Oceania",
"CK" : "Cook Islands",
"FM" : "Micronesia",
"KI" : "Kiribati",
"NR" : "Nauru",
"NC" : "New Caledonia",
"NU" : "Niue",
"PW" : "Palau",
"PG" : "Papua New Guinea",
"MH" : "Republic of Marshall Islands",
"WS" : "Samoa",
"SB" : "Solomon Islands",
"TO" : "Tonga",
"TV" : "Tuvalu",
"VU" : "Vanuatu",
"OM" : "Oman",
"PA" : "Panama",
"PE" : "Peru",
"PH" : "Phillipines",
"PK" : "Pakistan",
"PL" : "Poland",
"PS" : "Palestine",
"PY" : "Paraguay",
"QA" : "Qatar",
"RO" : "Romania",
"RS" : "Serbia",
"RU" : "Russian Federation",
"RW" : "Rwanda",
"SA" : "Saudi Arabia",
"SE" : "Sweden",
"SG" : "Singapore",
"SI" : "Slovenia",
"SK" : "Slovakia",
"SN" : "Senegal",
"SO" : "Somalia",
"SR" : "Suriname",
"SS" : "South Sudan",
"SV" : "El Salvador",
"TG" : "Togo",
"TH" : "Thailand",
"TJ" : "Tajikistan",
"TN" : "Tunis",
"TR" : "Turkey",
"TT" : "Trinidad and Tobago",
"TW" : "Taiwan",
"TZ" : "Tanzania",
"UA" : "Ukraine",
"UG" : "Uganda",
"ZW" : "Zimbabwe",
"US" : "United States",
"UY" : "Uruguay",
"UZ" : "Uzbekistan",
"VN" : "Vietnam",
"ZA" : "South Africa",
"ZM" : "Zambia",
"AG" : "Antigua and Barbuda",
"BB" : "Barbados",
"BT" : "Bhutan",
"CD" : "Democratic Republic of the Congo",
"Unknown" : "Unknown",
"FO" : "Faroe Islands",
"GL" : "Greenland",
"HN" : "Honduras",
"KW" : "Kuwait",
"MO" : "Macau",
"SD" : "Sudan",
"TC" : "Turks and Caicos Islands",
"MV" : "Maldives",
"GH" : "Ghana"
}

